STYLE_HOOKS = {
    "phonk": [
        "Don't play this at 3am 🌑",
        "This should be illegal 😈",
        "POV: night drive with no destination 🌙",
        "Nobody is talking about this song 😳",
        "The phonk you've been looking for 🔥",
        "This sound won't leave your head 🔁",
        "Found this at 2am and regretted nothing 😈",
        "This chord is a crime 🖤",
        "Save this before it disappears 📌",
        "Your playlist was incomplete until now 😳",
    ],
    "trap": [
        "What is this beat omg 🤯",
        "This is going in your playlist today 💎",
        "Nobody is listening to this yet 😳",
        "POV: you just found your new favorite 🔁",
        "This bass should be banned 🔥",
        "Save this video right now 📌",
        "Your playlist was asking for this 💎",
        "You found it before it blew up 👑",
        "Couldn't stop listening 😮",
        "This ain't for everyone 😈",
    ],
    "rock": [
        "This guitar will destroy you 🎸",
        "Impossible not to headbang 🤘",
        "What kind of riff is this 🔥",
        "Max volume mandatory ⚡",
        "This is criminally good 🎸",
        "Your rock playlist needed this 🔥",
        "Can't listen just once 🔁",
        "Wait for the drop 😤",
        "This will wreck your neck 🤘",
        "Nobody talked about this band like this 😳",
    ],
    "metal": [
        "This ain't for everyone ⚠️",
        "Your headphones can't handle this 🔥",
        "Warning: absurdly heavy 😈",
        "This drop is unreal 🤯",
        "Found hell in the form of music 🖤",
        "Prepare your neck 🤘",
        "This will destroy you in the best way 😈",
        "Heaviness level: illegal ⚠️",
        "Save this to listen in the dark 🌑",
        "Your playlist needed chaos 🔥",
    ],
    "lofi": [
        "Put this on and disappear 🎧",
        "Perfect for 3am ☁️",
        "This is what peace sounds like 🌙",
        "Listen while it rains 🌧️",
        "The study playlist you deserve 📚",
        "This calmed my anxiety instantly 😮",
        "POV: you finally relaxed 🌙",
        "Infinite loop guaranteed 🔁",
        "This sound hugs you 🎧",
        "Don't know what this is but I'm fine 🌿",
    ],
    "indie": [
        "You'll repeat this all week 🎧",
        "This sound stays with you 🌅",
        "The feeling you didn't know you needed 🌙",
        "Your next favorite song 🎵",
        "Found this and can't stop 🔁",
        "This one stays with you 🌌",
        "Whoever made this is a genius 😳",
        "Gets better with every loop 🎧",
        "POV: you found it before it went viral 👀",
        "Put headphones on and vanish 🌿",
    ],
    "electronic": [
        "This drop will break your brain 🤯",
        "What frequency is this?? ⚡",
        "Was not ready for this 🚀",
        "The drop you didn't see coming 🤯",
        "Does this even exist?? ⚡",
        "Max volume or don't bother 🔥",
        "This bass is unreal 😮",
        "Your gym playlist needs this ⚡",
        "This shouldn't sound this good 🤯",
        "Festival at home right now 🎉",
    ],
    "dark": [
        "Found you at the right moment 🌑",
        "Beautiful and haunting at the same time 🖤",
        "Don't listen to this alone 😳",
        "This sound carries an entire night 🌙",
        "Your soul needed this 🌑",
        "Can't get this chord out of my head 🖤",
        "This is scary in the best way 😈",
        "POV: 3am and this song 🌑",
        "Found the void and it has a melody 🖤",
        "This isn't for every hour 🌙",
    ],
    "default": [
        "Nobody is talking about this song 😳",
        "This is going in your playlist today 🎧",
        "POV: you just found the song of the month 🔁",
        "What is this sound?? 🤯",
        "Save this before it disappears 📌",
        "Couldn't listen just once 🔁",
        "You found it before it blew up 👀",
        "Your playlist was incomplete 🎵",
        "Loop guaranteed 🔁",
        "This is too good to be real 😮",
    ],
}
