name: Auto YouTube Upload

on:
  schedule:
    - cron: "0 */4 * * *"
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install moviepy pillow requests

      - name: Run script
        run: |
          python main.py
